greeting: true
show_logo: true
bar_cursor: true
prompt_symbol: "◯"
submitted_prompt_symbol: "⬤"
show_diff: false
show_thinking: true
show_turn_stats: false
redraw_counter: false
show_tools: full
show_messages: all-full
theme: auto
bind: {}
